### ISSUE TITLE
Quadsort as another idea to benchmark against

### ISSUE THREAD

**Issue by dumblob** [gerben-s/quicksort-blog-post#2]
At the end of your blog post you've even tried implementing CPU-pipeline-efficient MergeSort. What about enhancing [Quadsort](https://github.com/scandum/quadsort ) (which is MergeSort, but with a tiny sorting network built-in) by your `DistributeBackward` and `DistributeForward` approach?

**Comment by gerben-s** [comment]
I don't know. Feel free to try it :D and let me know if it pans out. I'd be interested to see the results.
